### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by drKraken**

### CODE REVIEW

**Comment by arthurvr** [comment]
Updating  yeoman-generator can't happen without other changes. 0.19 was a release with quite a bit of deprecations so you'll need to fix some stuff first.

**Comment by sindresorhus** [comment]
Please run tests locally before doing a before so we don't have go through this dance on every PR ;)

Example: https://github.com/sindresorhus/generator-nm/commit/95a98c3cc73a8107eb1b8b0ab708caf6dd3b2d76

**Comment by drKraken** [comment]
@arthurvr Sorry, seems to be fixed;

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request closed without merging**
